services:
  
  gateway:
    image: micros
    env_file:
      - ../.env
    environment:
      - SERVICE=api
    ports:
      - 42069:42069
      
  users:
    image: micros
    env_file:
      - ../.env
    environment:
      - SERVICE=users

  nats:
    hostname: nats
    image: nats
    ports:
      - 4222:4222

version: '3'
